service: lambda-dynamodb-example
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - arn:aws:dynamodb:us-east-1:461432510960:table/TaskTable

functions:
  hello:
    handler: src/hello.hello
    events:
      - httpApi:
          path: /
          method: get
  getTasks:
    handler: src/tasks.getTasks
    events:
      - httpApi:
          path: /tasks
          method: get
  getTaskById:
    handler: src/tasks.getTaskById
    events:
      - httpApi:
          path: /tasks/{id}
          method: get
  createTask:
    handler: src/tasks.addTask
    events:
      - httpApi:
          path: /tasks
          method: post
  updateTask:
    handler: src/tasks.updateTask
    events:
      - httpApi:
          path: /tasks/{id}
          method: put
  deleteTask:
    handler: src/tasks.deleteTask
    events:
      - httpApi:
          path: /tasks/{id}
          method: delete

resources:
  Resources:
    TaskTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: TaskTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
